//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TupleGeo.General.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TupleGeo.General.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=.
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_DataSource {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source not specified..
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_ExceptionDataSourceNotSpecified {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_ExceptionDataSourceNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting DataSource..
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_ExceptionGettingDataSource {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_ExceptionGettingDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting Initial Catalog..
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_ExceptionGettingInitialCatalog {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_ExceptionGettingInitialCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting Password..
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_ExceptionGettingPassword {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_ExceptionGettingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting Persist Security Info..
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_ExceptionGettingPersistSecurityInfo {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_ExceptionGettingPersistSecurityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting UserID..
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_ExceptionGettingUserID {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_ExceptionGettingUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Catalog not specified..
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_ExceptionInitialCatalogNotSpecified {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_ExceptionInitialCatalogNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error decrypting password. Initialization vector not specified..
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_ExceptionInitializationVectorNotSpecified {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_ExceptionInitializationVectorNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error decrypting password. Security key not specified..
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_ExceptionSecurityKeyNotSpecified {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_ExceptionSecurityKeyNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique UserID not found..
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_ExceptionUniqueUserIDNotFound {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_ExceptionUniqueUserIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID not found..
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_ExceptionUserIDNotFound {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_ExceptionUserIDNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID not specified..
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_ExceptionUserIDNotSpecified {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_ExceptionUserIDNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Catalog=.
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_InitialCatalog {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_InitialCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password=.
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_Password {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persist Security Info=.
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetails_PersistSecurityInfo {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetails_PersistSecurityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID=.
        /// </summary>
        internal static string Data_SqlServer_ConnectionDetials_UserID {
            get {
                return ResourceManager.GetString("Data_SqlServer_ConnectionDetials_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert property value to string..
        /// </summary>
        internal static string General_PropertyCouldNotConvertValueToString {
            get {
                return ResourceManager.GetString("General_PropertyCouldNotConvertValueToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property has more than one generic arguments..
        /// </summary>
        internal static string General_PropertyHasMoreThanOneGenericArguments {
            get {
                return ResourceManager.GetString("General_PropertyHasMoreThanOneGenericArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property is not of a primitive type..
        /// </summary>
        internal static string General_PropertyIsNotOfAPrimitiveTypeException {
            get {
                return ResourceManager.GetString("General_PropertyIsNotOfAPrimitiveTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; was not found..
        /// </summary>
        internal static string General_PropertyNotFound {
            get {
                return ResourceManager.GetString("General_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property nullable type is not of a primitive type..
        /// </summary>
        internal static string General_PropertyNullableTypeIsNotOfAPrimitiveType {
            get {
                return ResourceManager.GetString("General_PropertyNullableTypeIsNotOfAPrimitiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} not found in assembly..
        /// </summary>
        internal static string Reflection_AssemblyExtensions_ExceptionTypeNotFoundInAssembly {
            get {
                return ResourceManager.GetString("Reflection_AssemblyExtensions_ExceptionTypeNotFoundInAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} not found or more than one found in assembly..
        /// </summary>
        internal static string Reflection_AssemblyExtensions_ExceptionTypeNotFoundOrMoreThanOneTypesFoundInAssembly {
            get {
                return ResourceManager.GetString("Reflection_AssemblyExtensions_ExceptionTypeNotFoundOrMoreThanOneTypesFoundInAssem" +
                        "bly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret key and Initialization vector must not be null..
        /// </summary>
        internal static string Security_CryptographicString_ExceptionNullKeyOrInitializationVector {
            get {
                return ResourceManager.GetString("Security_CryptographicString_ExceptionNullKeyOrInitializationVector", resourceCulture);
            }
        }
    }
}
